import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <div className="flex min-h-screen flex-col items-center justify-center">
            <div className="container flex w-3/6 flex-col items-center justify-center rounded-lg border-4 border-solid border-[#F5F5F5] px-5 py-14">
              {children}
              <Toaster />
            </div>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
